### ISSUE TITLE
Small safari issues

### ISSUE THREAD

**Issue by mustafa0x** [DigitalKhatt/madinafont#1]
![image](https://user-images.githubusercontent.com/1473102/226791444-925d006c-bcf4-40b0-a390-e305e6a09fef.png)

---

![image](https://user-images.githubusercontent.com/1473102/226791452-eb870bbb-0fbb-431b-a54d-0828cf2cff85.png)

---

![image](https://user-images.githubusercontent.com/1473102/226791457-7b84c836-79cb-460e-b3d3-067ea4efed6b.png)

---

![image](https://user-images.githubusercontent.com/1473102/226791464-01cda4e5-6def-4872-8b33-34ded1760e36.png)

**Comment by aminanan** [comment]
I fixed the above issues except the basmalah. Very likely there will be other issues since it seems that Harfbuzz handles cursive and mark anchors very differently from Safari. I need to manually rewrite and rearrange several lookup tables.

**Comment by mustafa0x** [comment]
I did some testing and results were very nice.
جزاك الله خيرا!

> I need to manually rewrite and rearrange several lookup tables.

This is a bit upsetting. Safari is also a major pain point for me when working on general web development. Is there perhaps a way to automate this step?
