### ISSUE TITLE
ARABIC SMALL LOW MEEM should be under the ARABIC KASRA

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#10]
Currently the order is wrong. e.g. in
قَوْمِۭ

<img src="https://github.com/DigitalKhatt/madinafont/assets/2936425/786523cc-b874-4e81-acac-ea71c896ddab" width="100" />

**Comment by munzirtaha** [comment]
Today, I wouldn't say it's wrong because I found it written like this in other Mushafs and I couldn't find a reference that says it should be this way or the other. May be the size of the small meem is a bit large and needs tweaking.

I might do another review of the font current situation and report issues if this is useful to you but what's the difference between the font in madinafont repo and [this](https://github.com/DigitalKhatt/visualmetafont/blob/master/fonts/digitalkhatt/digitalkhatt.otf)?

**Comment by aminanan** [comment]
Fixed. I checked this in the Madinah Mushaf of 1441 Hijri. Indeed the small low meem is always under the kasra.

![Capture3](https://github.com/user-attachments/assets/c0b45c42-41d7-43cb-8b74-efc1d5f2dad2)

**Comment by munzirtaha** [comment]
Thanks
