### ISSUE TITLE
FATHA and KASRA positions are incorrect

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#12]
أَنشَأَكُم ۝ ٱلْأَقْرَبِينَ ۝

![Screenshot_20230731_150711](https://github.com/DigitalKhatt/madinafont/assets/2936425/5c39fa0a-c5d2-4e29-b083-a3193844f118)

**Comment by aminanan** [comment]
Fixed.

![Capture4](https://github.com/user-attachments/assets/bd22fa64-beba-49e0-8f41-aa76ea856377)

**Comment by munzirtaha** [comment]
The KAF is still different than in Mushaf which look like this:
![أنشأكم](https://github.com/user-attachments/assets/3aada061-d61f-4ce4-b6d3-6185bfd06876)

**Comment by aminanan** [comment]
Added new ligature and Alef short variants.

![Capture](https://github.com/user-attachments/assets/356c9bed-23f9-45c9-847f-95081b212eae)

**Comment by munzirtaha** [comment]
Thanks for the quick fix.
