### ISSUE TITLE
Wrong spacing after ARABIC REH and MADDAH ABOVE

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#13]
دُبُرَهُۥٓ إِلَّا ۝  أَوْلِيَآءَهُۥٓۚ إِنْ أَوْلِيَآؤُهُۥٓ إِلَّا۝
طَٰٓئِرࣲ يَطِيرُ بِجَنَاحَيْهِ۝ يُجْزَ بِهِ ۝ وَأَنذِرْ بِهِ ۝ يَمْكُرُ بِكَ ۝  وَٱلْأَحْبَارُ بِمَا ۝ وَسَارَ بِأَهْلِهِۦٓ
![Screenshot_20230731_151930](https://github.com/DigitalKhatt/madinafont/assets/2936425/3b7c0885-ceca-4719-bf90-3df7e9779477)

**Comment by aminanan** [comment]
Fixed.

![Capture6](https://github.com/user-attachments/assets/a3e82df2-80cb-43f0-9046-ebbb70009785)
