### ISSUE TITLE
ARABIC SMALL HIGH WAQF signs positions could be improved

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#14]
ٱلثَّمَرَٰتِۚ كَذَٰلِكَ ۝ عَامِلࣱۖ 
![Screenshot_20230731_154555](https://github.com/DigitalKhatt/madinafont/assets/2936425/26a16961-4519-4498-af9c-77278b5bc5c2)

- Isn't it better if the ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA be in a higher level than normal diacritics?

**Comment by aminanan** [comment]
Fixed.

![Capture5](https://github.com/user-attachments/assets/e2137504-54cd-4f40-a9b9-defd5b418e84)
