### ISSUE TITLE
الهمزة المكسورة الابتدائية

### ISSUE THREAD

**Issue by hubaishan** [DigitalKhatt/madinafont#16]
هذا الخطأ تابع [للخطإ السابق](https://github.com/DigitalKhatt/madinafont/issues/7#issue-1762355966) ولكن مع كون الهمزة ابتدائية
مثاله:
* ( أسمائهم) من البقرة:33 
* بارئكم- البقرة:54
* وقثائها - البقرة:61
*  خائفين - البقرة:114
* للطائفين-البقرة:125
والمواضع كثيرة جدًا 

وأيضا اللؤلؤ من الواقعة:23 لم تصحح

**Comment by aminanan** [comment]
I uploaded a new font. Can you check please? (You have to put a kasra for the rule to apply). Here are some examples.

![Capture](https://github.com/user-attachments/assets/a5b36f22-3f09-4448-8c24-848fbb395603)

**Comment by aminanan** [comment]
Please reopen the issue if you still find a problem.
