### ISSUE TITLE
kerning, collisions, and other issues

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#17]
ٱلْخَٰشِعِينَ ۝ وَّإِن ۝ مَلْجَـًٔا ۝ ٱلسَّيِّـَٔاتِ ۝ قَبْرِهِ ۝ حَقࣰّا ۝ نَجِيࣰّا ۝ مِنكُمْۚ ۝ مِسْكࣱۚ ۝ ذِلَّةٌۚ أُو۟لَٰٓئِكَ ۝ رَّسُولࣱۖ فَإِذَا ۝ قَلِيلࣱۗ فَلَا ۝ ٱلْحَقَّۖ فَهُم ۝ ٱلْحَقُّۖ فَمَن ۝ مُفْتَرَيَٰتࣲ ۝ وَلَٰكِنِّيٓ ۝ مَوْجࣲ ۝ بِتَارِكِيٓ ۝ خُبْزࣰا ۝ رُحْمࣰا ۝ خَلْقًا ۝ أُورِثْتُمُوهَا ۝ شَيْـࣰٔا ۝ ٱلْقَهَّٰرُ ۝ فَلِلَّهِ ۝ ٱلضُّعَفَٰٓؤُا۟ ۝ هَٰٓؤُلَآءِ ۝ لَبِإِمَامࣲ ۝ لَـَٔاتِيَةࣱ ۝ أَثْقَالَكُمْ ۝ أَلْوَٰنُهُۥٓۚ ۝ تُشَٰٓقُّونَ ۝ وَلَلْـَٔاخِرَةُ ۝ لِّلْـَٔاكِلِينَ ۝ ٱلزِّنَىٰٓۖ ۝ ثَبَّتْنَٰكَ ۝ فَٱنطَلَقَا ۝ أَوْزَارࣰا ۝ وَنَذِيرࣰا ۝ عِوَجَ ۝ أَحْلَٰمِۭ بَلِ ۝ تُرَٰبَۢا۝ عِلْمِۭ بِٱلْمَلَإِ ۝ ٱلْحَقُّۖ لَآ ۝ مَّحْفُوظࣰاۖ۝ تَمَنَّىٰٓ ۝ ٱمْرِئࣲ ۝ قُلُوبِهِم ۝ لُجَّةࣰ ۝ أَسَٰٓـُٔوا۟ ۝ كَآفَّةࣰ ۝ لَنَرْجُمَنَّكُمْ ۝ لِّلشَّٰرِبِينَ ۝ عِوَجࣲ ۝ أَسَٰٓـُٔوا۟ ۝ فُرُشِۭ ۝ أَنَّهُم ۝ يُسَلِّطُ ۝ أَنزَلَهُۥٓ ۝ لَّجُّوا۟ ۝ أَيُّهُم ۝ ٱمْرِئࣲ ۝ وَأَبࣰّا ۝ ثُبُورࣰا ۝ لَوْحࣲ ۝ ٱلْحَٰكِمِينَ
![digitalkhatt](https://github.com/DigitalKhatt/madinafont/assets/2936425/427dadc7-9648-4084-9bb2-a2c33bb0c26a)

**Comment by aminanan** [comment]
Fixed. Here is the new result. If you still see a problem, please create a new issue specific to a particular problem.

![Capture2](https://github.com/user-attachments/assets/71f5dfb9-6442-4dfe-8b7a-539c752ef3a6)

**Comment by munzirtaha** [comment]
Thank you so much. I will open another issue per your request
