### ISSUE TITLE
KAF + ALEF WITH HAMZA BELOW is rendered incorrectly

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#20]
كإ

![kaf](https://github.com/user-attachments/assets/cdc432ae-4967-47b8-a09e-9ead86dd9068)

**Comment by aminanan** [comment]
Fixed.

![Capture](https://github.com/user-attachments/assets/95ba1259-5c8e-4bf2-b4b1-a9d2b6fb8469)

**Comment by munzirtaha** [comment]
Thanks!
