### ISSUE TITLE
خطأ في طريقة كتابة لفظ الجلالة في حالتين

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#22]
فَلِلَّهِ ۝  واللّٰه

![Screenshot_20240814_100451](https://github.com/user-attachments/assets/fb7fc793-2ca1-4417-a761-207309eea680)

**Comment by hubaishan** [comment]
فَلِلَّهِ:  موجودة في القرآن في أكثر من موضع منها [[الأنعام](https://ar.wikisource.org/wiki/مستخدم:حبيشان/ملعب#سورة_الأنعام):149] ورسمها خطأ كما ذكرت

لكن (والله) غير مستعمل في نص القرآن، المستعمل (وٱلله) بهمزة وصل وهو يظهر بشكل سليم
راجع للنص كاملا https://ar.wikisource.org/wiki/مستخدم:حبيشان/ملعب

**Comment by aminanan** [comment]
I uploaded a new file. Here is the result for the following text : واللّٰه ۝ بِٱللَّهِ ۝ فَلِلَّهِ ۝ وَٱللَّهُ

![Capture](https://github.com/user-attachments/assets/0bd9f76c-0cad-4ce3-b613-169a9fc83e0a)

**Comment by aminanan** [comment]
جزاك الله خيرا  @hubaishan على [النص](https://ar.wikisource.org/wiki/%D9%85%D8%B3%D8%AA%D8%AE%D8%AF%D9%85:%D8%AD%D8%A8%D9%8A%D8%B4%D8%A7%D9%86/%D9%85%D9%84%D8%B9%D8%A8#%D8%B3%D9%88%D8%B1%D8%A9_%D8%A7%D9%84%D9%88%D8%A7%D9%82%D8%B9%D8%A9).

For basmala you can add `font-feature-settings: 'basm'` to get 

![Capture](https://github.com/user-attachments/assets/ec1fe12a-06f8-4970-88cd-4ea709903d69)

**Comment by munzirtaha** [comment]
نعم أنا أعلم أن المصحف مكتوب بتشكيل كامل لكن التشكيل أمر اختياري ومعظم البرامج تتيح خيار إرسال الآية بدون تشكيل فلا ينبغي حين حذفه كله أو بعضه أن تصير الكتابة خاطئة

**Comment by hubaishan** [comment]
النص أذكر أني أخذته من مخزن موقعكم، وهو متوفر بصيغة جسون في ويكي مصدر:
https://ar.wikisource.org/wiki/module:Quran/data_DKhatt.json
لمن أراد الاستفادة منه بأي طريقة.

**Comment by hubaishan** [comment]
> نعم أنا أعلم أن المصحف مكتوب بتشكيل كامل لكن التشكيل أمر اختياري ومعظم البرامج تتيح خيار إرسال الآية بدون تشكيل فلا ينبغي حين حذفه كله أو بعضه أن تصير الكتابة خاطئة

جهودك مشكورة استاذ @munzirtaha  بعد إذن @aminanan   نص القرآن بالقراءات في ويكي مصدر أنا القائم عليه إذا عندكم ملاحظات لا تبخل علينا والتبليغ في صفحة نقاش الصفحات هناك، واعتذر عن الخروج عن الموضوع لأني لم أجد وسيلة للتواصل مع الاستاذ منذر.

**Comment by munzirtaha** [comment]
@hubaishan: بارك الله فيك وإن شاء الله لو ظهرت لي ملاحظة أبلغكم بها
@aminanan:  جزاك الله خيرا
