### ISSUE TITLE
Several examples of wrong kerning or diacritics position

### ISSUE THREAD

**Issue by munzirtaha** [DigitalKhatt/madinafont#4]
![dk](https://user-images.githubusercontent.com/2936425/233245166-97555581-45f3-45fd-a276-9930cf1ce286.png)

**Comment by munzirtaha** [comment]
Another wrong FATHA
![ataytukum](https://user-images.githubusercontent.com/2936425/232327184-abc6b5fe-910c-44ef-8f1e-1c56a0d271d6.png)

**Comment by mustafa0x** [comment]
consider adding these sort of issues to #2.

**Comment by munzirtaha** [comment]
@mustafa0x
The problem with putting them all in one issue, it will be so difficult to track which is fixed and which is not. But you as you did you can make that a meta bug where you link all the issues there. I also want to ask whether @aminanan wants us to report such issues or he is already aware of them?

**Comment by munzirtaha** [comment]
The issue with the word ٱلصَّٰبِرِينَ is highlighted with red here
![sabreen](https://user-images.githubusercontent.com/2936425/233249654-5dc9aa63-b7f5-4a14-872d-cf0ad7666b36.png)

**Comment by munzirtaha** [comment]
![n](https://user-images.githubusercontent.com/2936425/233363456-2437e42a-8ba4-462c-b52d-2ca0b46011dc.png)

**Comment by aminanan** [comment]
@munzirtaha, can you send the unicode text of the examples with errors above, if you have it ? Thanks.

**Comment by munzirtaha** [comment]
Unfortunately, I did a stupid thing and haven't saved the file. I should have attached it here, not just the screenshot.

**Comment by aminanan** [comment]
No problem. Next time then.

**Comment by aminanan** [comment]
Done. If there are other collision or positioning problems, please create a new issue for each problematic glyph (or combination of glyphs) with the corresponding Unicode text. Thanks.
![Capture](https://github.com/DigitalKhatt/madinafont/assets/33678118/fd58ca14-165a-423b-866d-09b4641456e7)

**Comment by munzirtaha** [comment]
Will do. Thanks!
