### ISSUE TITLE
Rendering issue Alif-Khanjariya disconnects letters

### ISSUE THREAD

**Issue by danglingneuron** [DigitalKhatt/madinafont#5]
I am facing an issue with the new madina OTF font rendering Alif-Khanjariya. 

**Am I missing a specific font setting?**
 NOTE: I am using Uthmanic text from Quran.com API
![Screenshot 2023-04-17 114203](https://user-images.githubusercontent.com/12782664/232553594-8bb454e3-5972-41aa-ac7d-e9b53ae9d250.png)

Please note that the previous version (image below) also displays the same issue (downloaded WOFF from https://digitalkhatt.org/about)

![Screenshot 2023-04-17 114831](https://user-images.githubusercontent.com/12782664/232555203-56d0dec5-f3e8-4aa0-95cd-cbae4d2526f3.png)

**Comment by mustafa0x** [comment]
This is due to small alif + tatweel. Tanzil's text doesn't have, so use that. Might be nice if this font could support both. The quran text I worked on also uses a tatweel for the small alif.
