### ISSUE TITLE
OTF file fails conversion to WOFF

### ISSUE THREAD

**Issue by danglingneuron** [DigitalKhatt/madinafont#6]
Can you please provide WOFF file for web/mobile usage. The current OTF file is 1.2mb in size. I have tried several online tools to convert to WOFF but it fails.

Also the OTF file fails to open on a windows machine.

**Comment by aminanan** [comment]
You can use the ``ttx`` command of [fonttools](https://github.com/fonttools/fonttools)
```
pip install fonttools[woff]
```
Generate XML ttx file :
```
ttx digitalkhatt.otf digitalkhatt.ttx
```
Compile WOFF2 format :
```
ttx --flavor woff2 digitalkhatt.ttx
```
Compile WOFF format :
```
ttx --flavor woff  digitalkhatt.ttx
```
or
```
ttx --flavor woff --with-zopfli digitalkhatt.ttx
```
The OTF file uses the CFF2 format which seems to cause problems under Windows. There are probably tools that can convert it to a compatible format. Unfortunately at the moment I don't have time to deal with this problem. Anyway, if you want this problem to be fixed sooner or later, please create a new issue for it.

I added [digitalkhatt.woff2](https://github.com/DigitalKhatt/madinafont/blob/main/digitalkhatt.woff2?raw=true)  to the repository.
