### ISSUE TITLE
خطأ في تركيب الخط

### ISSUE THREAD

**Issue by tlha111** [DigitalKhatt/madinafont#8]
السلام عليكم ورحمة الله

الخط جميل جدا
ولكن وجدت تداخلا بين حرفين في كلمة: خنزير.

أرجو إصلاحه 

كذلك لا أستطيع تثبيت الخط على وندوز 11 ولا وندوز 10 يظهر لي خطأ.
![IMG_20230619_192458_865](https://github.com/DigitalKhatt/madinafont/assets/137083159/9a2c6f49-75dd-44b3-bf8e-c102d2399b75)
![Screenshot_٢٠٢٣٠٦١٨_١٦٥١٤٢_Chrome](https://github.com/DigitalKhatt/madinafont/assets/137083159/e819730e-39f0-4b80-9430-36aaafcee92b)

**Comment by aminanan** [comment]
Regarding the Windows error, please see the end of [this comment](https://github.com/DigitalKhatt/madinafont/issues/6#issuecomment-1512298026)
