### ISSUE TITLE
13 line Mushaf

### ISSUE THREAD

**Issue by WhatIsntAvailable** [DigitalKhatt/madinafont#9]
AssalamuAlaykum,

Hope you are well.

I was thinking of making a 13 line Mushaf (pdf/app) for the Reciters of Ashaab al-Tawassut. This work has already been done for the 15 line Mushaf as an app as well as a pdf. 

Would making a 13 line mushaf for this be something you can help with? If not, do you have any guidelines on how i can use your font/typeset, to type out the 13 line mushaf.

[أصحاب التوسط.pdf](https://github.com/DigitalKhatt/madinafont/files/11885117/default.pdf)

Please see the 15 line Mushaf file for this attached.

Hope to hear from you soon.

Jzk.
Huzaifah

**Comment by aminanan** [comment]
Wa Alaikum Assalam,

What text software was used to typesety the Mushaf above ?

**Comment by WhatIsntAvailable** [comment]
Assalaamualaykum,

Thank you for getting back to me.

I'm not sure to be honest. This is just the file my teacher gave and I want
to make a 13 line version of it.

Huzaifah.

**Comment by aminanan** [comment]
Wa Alaikum Assalam,

The font is a standard OpenType font using the CFF2 table. You should be able to use any software that supports this type of font such as LuaLaTeX or HTML5/CSS3.
